---

- hosts: all
  become: true
  pre_tasks:

  - name: Install Updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install update (CentOS)
    tags: always
    dnf:
       update_only: yes
       update_cache: yes
    when: ansible_distribution == "CentOS"


- hosts: web_server
  become: true
  tasks:

  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Install Docker (CentOS)
    command: snap install docker
    when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:

  - name: Install Docker (Ubuntu)
    apt:
      name:
        - docker.io
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: Install Docker (CentOS)
    command: snap install docker
    when: ansible_distribution == "CentOS"
